### ISSUE TITLE
Informações do repositorio.

### ISSUE THREAD

**Issue by ghost** [Luna1345/fluffy-succotash#1]
Estava olhando aqui, sobre o que seria esse repositório?
Da uma explicada e fala quais linguagens serão usadas para o desenvolvimento.

**Comment by Luna1345** [comment]
Vou usar Python

Em qua, 10 de fev de 2021 11:32, Yoda <notifications@github.com> escreveu:

**Comment by ghost** [comment]
Boa, sucesso com seu projeto ai, depois que começar a publicar irei analisar.
